"""DD-1 batch: Video/content pipeline subsection collapse (Sep 23 2026, batch 3)."""

ARCHIVE_HEADER = "## Video / content pipeline domain narrative — collapsed from CLAUDE.md Sep 23 2026 (DD-1 batch 3, real Oversight Doc Dedup & Compression pass)\nFull dated stories, verbatim, moved here per the July 31 collapse rule. Each now has a real anchor link from CLAUDE.md's own durable one-liner into the matching patch_notes.html card."

BULLETS = [
    ('**"Delete doesn\'t stick" (videoSummary._delete',
     '- **"Delete doesn\'t stick" fixed Aug 27**: a real `intel_reanalysis_pool` table + `encyclopedia.source_url` column suppress a merge candidate only if it\'s the same age or older than a real deletion (never a permanent per-URL ban) — `local_server.py`/`rpgace_intel.py` brought into the repo and fixed with the same discipline. [Full story](patch_notes.html#card-2026-08-27-delete-doesn-t-stick-fixed-videosummary).'),
    ('**Massive Expansion plan (`ceo_plans` "Massive Expansion") build-out',
     '- **Massive Expansion build-out shipped Aug 23-24 (8 items, 1 confirmed blocked)**: Fallback Scout delete buttons (A3); a real 61%-of-insights-silently-discarded bug fixed in Content Intelligence (A4/A8); OBS-raw as a real 3rd Content Pipeline workflow (A7); the Quest Board\'s first real Supabase persistence via `questEngine` (A9 Phase 1); Bibliography consolidated into Chronicles + a dormant taxonomy branch (A6/A15). A10 (Oracle-as-orchestrator via Kimi/Luna) stays genuinely blocked — no key, no answer yet on which sub-tasks would route there. [Full story](patch_notes.html#card-2026-08-24-session-closed-via-bedtime-massive-expansion).'),
    ('**A5 shipped in full Aug 15, both passes same day',
     '- **A5 shipped in full Aug 15 — Research Lab is fully retired**, not just narrowed: Idea Bank/Beat Log/Upload Workshop open directly from Content Pipeline, File Analyzer/Video Finder moved to Bookworm. A real "worm family" vision (Videoworm/Articleworm/MusicWorm) surfaced and is explicitly NOT built. [Full story](patch_notes.html#card-2026-08-15-36th-pass-a5-phase-1-shipped).'),
    ('**A5 Phase 2, slice 1+2 shipped Aug 22',
     '- **A5 Phase 2, slice 1+2 shipped Aug 22**: Idea Bank\'s "+ Create new via Oracle" button, and a real repurpose-merge (Instagram/Shorts/TikTok content merges into one section when genuinely identical, saving tokens). 2 pieces stay honestly unbuilt: Corpus\'s taxonomy-tree feed claim, Upload Workshop\'s strategy-generation button. [Full story](patch_notes.html#card-2026-08-22-a5-phase-2-slice-1-2).'),
    ('**A2 shipped Aug 22 (via `/Routine`) — the Dummy/Fallback',
     '- **A2 shipped Aug 22**: the Dummy/Fallback Oracle mode banner no longer overlaps real page content — `_pushBodyBelow()` pushes `body`\'s padding-top by the badge\'s own measured height. [Full story](patch_notes.html#card-2026-08-22-a2-dummy-fallback-oracle-banner-no).'),
    ('**Aug 22 (real follow-up, same day) — 4 real fixes',
     '- **Aug 22 follow-up, 4 real fixes from Alex\'s hand-test**: dev-chrome (Oracle Mode switch/badge/etc.) now hides until real login via `hideUntilLogin()`; the 3 floating pills consolidated into one shared dev-status-cluster panel; a duplicate YouTube Oracle button injector removed; `morningBrief._autoRun()` fixed to wait for the real login hook instead of a blind boot timer. [Full story](patch_notes.html#card-2026-08-22-real-hand-test-follow-up-login-gate-chrome-hidden).'),
    ('**Aug 22 (2nd hand-test follow-up, same day) — real 2nd redesign',
     '- **Aug 22 2nd redesign pass**: the dev-status bar is now a real permanent bar with a collapsed reveal-on-press cluster. A real, definitive fix for the recurring "boot task failed" warning: `taxonomySync.getTopGaps()`/`bookworm._refreshWidget()` both called `RPGACE.sb.select` before `config.init()` set it — fixed with the same guard `dashDeck._refreshGlance` already used. [Full story](patch_notes.html#card-2026-08-22-collapsible-oracle-mode-panel-boot-task-select).'),
    ('**The separate "📹 Video Pipeline" dashDeck card is GONE',
     '- **The separate "📹 Video Pipeline" dashDeck card is gone (Aug 6)** — every `video_jobs` row was always created by `beatLog._submit`; its logic is unchanged, now rendered inline inside a ConID\'s Production Panel Phase 4 instead of a separate popup. [Full story](patch_notes.html#card-2026-08-06-engineer-real-deduplication-pass-video-pipeline).'),
    ('- Shipped July 30-31 and **all untested**',
     '- **Slice A + a UX pass shipped July 30-31 (all untested)**: return-to-Beat-Log nav, auto-advance stage triggers, corpus backfill popup, Director Match toasts, Generate Beatstars Listing rename, FK-aware ConID delete, music_video 4-step display labels, Script+Treatment handoff view. [Full story](patch_notes.html#card-2026-07-30-routine-engineer-video-pipeline-slice-built).'),
    ('**Content/Video Pipeline unification (Aug 5) — a real `/interrogation`-scoped 8-phase',
     '- **Content/Video Pipeline unification shipped Aug 5, an 8-phase build (A-H)**: mood-aware colour palette; Director Match blends up to 3 directors; music_video ConIDs get a real 4-phase Production Panel (Reference+Style/Direction+Script/Script Editing/Video Pipeline); a real OpenMontage-handoff payload behind a freeze flag; "Generate Captions" pulls real command text from Insta/YouTube/a new `tiktokOracle` module for all 3 short-form platforms; a real deliverables bucket + server-side zip mechanism for stems/tiers. Phase B (real audio-similarity audience matching) was stopped, not built on the wrong premise. [Full story](patch_notes.html#card-2026-08-05-session-closed-via-bedtime-real-state).'),
    ('**Content Pipeline UX overhaul (Aug 6, `/Engineer` pass 12)',
     '- **Content Pipeline UX overhaul (Aug 6)**: a ConID card\'s buttons are now stage-aware (one primary action + one redo-last-stage button) via 4 new lookup tables, instead of a fixed button set regardless of real progress; Beatstars Listing + Manage Deliverables folded behind a "💰 Sell This Beat" toggle. [Full story](patch_notes.html#card-2026-08-06-engineer-pass-12-content-pipeline-ux).'),
    ('**"Content Production Live" vs. "Content Pipeline" — real `/scope`+GODMODE',
     '- **"Content Production Live" vs. "Content Pipeline" — real dedup check (Aug 6), verdict: not a code duplication, was a real branding bug.** There has only ever been one real list/tracker implementation (`#cpl-widget` is moved into the dashDeck popup, never rebuilt) — fixed the header\'s confusing eyebrow/title stack to one consistent brand voice. [Full story](patch_notes.html#card-2026-08-06-real-scope-godmode-dedup-check-content).'),
]
