"""DD-1 batch: External-handoff-lanes subsection collapse (Sep 23 2026, batch 5).
Note: these bullets are bare paragraphs (no leading '- '), matching this
project's own existing local formatting convention for the Aug 11 cascade."""

ARCHIVE_HEADER = "## External-handoff-lanes domain narrative, part 2 — collapsed from CLAUDE.md Sep 23 2026 (DD-1 batch 5, real Oversight Doc Dedup & Compression pass)\nFull dated stories, verbatim, moved here per the July 31 collapse rule."

BULLETS = [
    ("**Aug 4 — free local/cloud GPU path for the Colibri music video PAUSED",
     '- **Aug 4 — free local/cloud GPU path for the Colibri music video PAUSED** (Alex\'s call), superseded by a paid-provider search. Real work kept, not deleted: the LTX-2/hunyuan-1.5 variant-loading code fixes live on `fix/hunyuan-ltx2-variant-loading` in the OpenMontage repo, independent of which generation path RPGACE ends up using. [Full story](patch_notes.html#card-2026-08-04-colab-kaggle-free-gpu-integration-scoped-not).'),
    ('**Real rename, Aug 13 — "Engineer CC" is retired',
     '- **Real rename, Aug 13 — "Engineer CC" is retired; every current-state doc now says "OpenMontage CC."** Alex\'s own direct call: the old name collided with `/Engineer`, a skill living inside THIS session — it never ran that skill, it\'s the separate Claude Code session operating `calesthio/OpenMontage`. Fixed in `total_system_members`, `ai_tooling_and_rules_map.md`, `manual.html`, `interconnection_map.md`, `minotaur_map.html`, `.claude/skills/misunderstanding/SKILL.md`, `scripts/graphify_river_group.py`. **Every dated bullet BELOW this one that still says "Engineer CC" is historical narrative, left as-said.** [Full story](patch_notes.html#card-2026-08-13-engineer-cc-retired-now-openmontage-cc).'),
    ('**Real extension, Aug 11 (A13 of the massive-expansion spec',
     '**A13 of the massive-expansion spec (Aug 11): the real report shape every Total dispatch comes back with, plus a real reconciliation loop.** Every real task dispatched to any Total member should report both an OUTPUT (what was actually done, real errors never swallowed) and INFRASTRUCTURE KNOWLEDGE (what the dispatch revealed about how that member\'s own system works) — then `/drift`+`/paranoia` check the combined picture against the original goal, iterating until nothing\'s left. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-prompt-caching-shipped).'),
    ('**Real extension, Aug 11 (2nd, same day) — Oversight is now scoped to the whole Total system',
     '**Oversight is scoped to the whole Total system, not RPGACE-internal architecture alone (Aug 11, Alex\'s own correction).** All 16 rivers (not "11 rivers + 5 zones") — River XII (`api/*.js`) is the layer every external Total-system call routes through; Rivers XIII-XVI carry the dev-process/knowledge layer. 2 real bugs fixed the same pass: a non-deterministic tie-break in river assignment, and a legend-duplication bug on repeated script runs. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-real-combined-view).'),
    ('**Real, deserved correction, Aug 11 (same day) — `minotaur_map.html` had drifted',
     '**`minotaur_map.html` had drifted into a changelog (Aug 11) — Alex called it out directly and correctly.** A full sweep (not spot patches) rewrote every dated/changelog-style node title into present tense; River IX\'s OpenMontage channel (whose real spring AND mouth both sit in River XI) now drawn explicitly instead of left implicit. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-real-deserved-critique).'),
    ('**76 loose spec/backlog/debate files physically archived',
     '**76 loose spec/backlog/debate files physically archived (Aug 11) — repo root no longer littered.** All 76 moved via `git mv` (history preserved) into `records/2026-07/`/`records/2026-08/`, by real filename date or mtime; 11 genuinely live files stay at root. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-76-loose-spec).'),
    ('**Real extension, Aug 11 (4th, same day) — the archive-report/"current capabilities" diagnostic',
     '**The archive-report/"current capabilities" diagnostic + real Supabase row-level dedup (Aug 11).** `scripts/supabase_dedup_scan.py` built and run for real (9 tables + `taxonomy_tree`) — 2 genuine duplicates found, flagged for Alex, not auto-merged (no Supabase backup exists). `style_profiles`\'s stale "0 rows ever" claim fixed to 3 rows, the real finding that proved the staleness gap wasn\'t hypothetical. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-archive-report-current-capabilities).'),
    ("**Real extension, Aug 11 (5th, same day) — `/paranoia`+`/CEO` on minotaur_map.html's own River XII-XVI",
     '**`/paranoia`+`/CEO` on minotaur_map.html\'s River XII-XVI (Aug 11): Alex was right, the missing interlinks were real and already visible in graphify/Obsidian.** `RIVER_FLOWS` had zero entries for rivers 12-16 despite them being real peer rivers — fixed with 13 new grepped, evidence-based entries; `minotaur_map.html` gained matching `.river-flow-next` connectors. [Full story](patch_notes.html#card-2026-08-11-same-day-continued-paranoia-ceo-minotaur_map).'),
]
