#!/usr/bin/env python3
"""
generate_method_module_map.py — Aug 26 2026, real Alex ask ("an error function
for each module... flag purple... tied to error log").

Real technical finding this script exists to work around: RPGACE.register()
modules are plain object literals (RPGACE.register('beatLog', { _submit:
function(){...} })), so a V8 stack trace for an error thrown inside a real
method reports it generically as "Object._submit" — the enclosing module
name is NOT present in the trace at all (confirmed via a real headless
Chromium test against the live minified app, not assumed). mangle:false
(this project's own permanent minify setting) DOES preserve every real
method NAME, though — so a real, viable attribution technique is: build a
method-name -> owning-module(s) lookup table ONCE, at commit time, from the
real source, and use it client-side to resolve "Object._submit" back to
"beatLog" whenever exactly one module defines that method name. A method
name defined by 2+ modules (e.g. the many generic _inject/_render/init
methods every module has) stays honestly AMBIGUOUS — never guessed.

This is a real, standalone generator script, same convention as the Galaxy
Map's own scripts/graphify_river_group.py family — reads rpgace_core.js
directly, writes nothing back to it. Run this, then paste its printed JS
object literal into errorLog.METHOD_MODULE_MAP (rpgace_core.js) by hand,
same "regenerate then re-embed" discipline update-logging-system already
uses for the Galaxy Map pipeline. Re-run whenever a module gains/loses/
renames a method — a stale table just means an attribution silently
degrades to ambiguous, never wrongly attributes (fails open, same as
everywhere else in this project).
"""
import re
import sys
import json
from pathlib import Path
from collections import defaultdict

SRC = Path(__file__).resolve().parent.parent / 'rpgace_core.js'

# Matches "RPGACE.register('moduleName', {" — the one real module
# convention this whole project uses (CLAUDE.md's own standing rule).
MODULE_RE = re.compile(r"RPGACE\.register\('([A-Za-z0-9_]+)',\s*\{")

# Matches a real object-literal method definition inside a module body:
#   methodName: function(
#   methodName: function (
# Deliberately does NOT match arrow-function/const-style methods since
# this codebase's own established module convention (confirmed via direct
# grep across many modules already read this session) is exclusively the
# "name: function() {}" object-literal shape.
METHOD_RE = re.compile(r"^\s*([A-Za-z0-9_]+):\s*function\s*\(", re.MULTILINE)


def _module_bodies(text):
    """Yields (module_name, body_text) for every real RPGACE.register(...)
    block, found by real brace-depth matching from the block's own opening
    '{' — not a naive regex-to-next-register, which would silently include
    unrelated code between modules if brace matching is skipped."""
    for m in MODULE_RE.finditer(text):
        name = m.group(1)
        start = m.end() - 1  # position of the opening '{'
        depth = 0
        i = start
        while i < len(text):
            c = text[i]
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    yield name, text[start:i + 1]
                    break
            i += 1


def build_map():
    text = SRC.read_text(encoding='utf-8')
    method_to_modules = defaultdict(set)
    module_count = 0
    for module_name, body in _module_bodies(text):
        module_count += 1
        for mm in METHOD_RE.finditer(body):
            method_to_modules[mm.group(1)].add(module_name)
    return method_to_modules, module_count


def main():
    method_to_modules, module_count = build_map()
    # Only keep UNAMBIGUOUS entries (exactly one owning module) — an
    # ambiguous method name (defined by 2+ modules) is real, useful
    # negative information (never attribute a guess), so it's reported
    # separately for visibility, not silently dropped from the printout.
    confident = {k: sorted(v)[0] for k, v in method_to_modules.items() if len(v) == 1}
    ambiguous = {k: sorted(v) for k, v in method_to_modules.items() if len(v) > 1}

    print(f'// Generated by scripts/generate_method_module_map.py — {module_count} real modules scanned,')
    print(f'// {len(confident)} unambiguous method names, {len(ambiguous)} ambiguous (skipped, listed below).')
    print('// Paste the object below into errorLog.METHOD_MODULE_MAP verbatim.')
    print('{')
    for k in sorted(confident):
        print(f'  {json.dumps(k)}: {json.dumps(confident[k])},')
    print('}')
    print()
    print(f'// {len(ambiguous)} ambiguous method names (defined by 2+ modules, real reason no wrong guess is possible):', file=sys.stderr)
    for k in sorted(ambiguous)[:25]:
        print(f'//   {k}: {ambiguous[k]}', file=sys.stderr)
    if len(ambiguous) > 25:
        print(f'//   ... and {len(ambiguous) - 25} more', file=sys.stderr)


if __name__ == '__main__':
    main()
